refine

diff --git a/runner_template b/runner_template
--- a/runner_template
+++ b/runner_template
@@ -4,30 +4,43 @@ Here=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURC
 source "$Here"/task.bash
 
 main() {
-  task "my changed" echo 'hello there!'
+  task 'my changed' echo 'hello there!'
   section mysection
 }
 
 mysection() {
-  task "my loop" echo '$1' <<'  END'
+  task 'my loop' echo '$1' <<'  END'
     one
     two
   END
 
-  task "my not run"
+  task 'my not run'
   ok true
   def not run
 
-  task "always fails due to ok"
+  task 'always fails due to ok'
   ok false
-  def echo "always fails due to ok"
+  def echo 'always fails due to ok'
 
-  task "always fails due to error"
+  task 'always fails due to error'
   def() {
-    echo "always fails due to error" >&2;
+    echo 'always fails due to error' >&2;
     false
   }
   run
+
+  task 'regular loop'
+  def echo '$1' <<'  END'
+    one
+    two
+  END
+
+  task 'function loop'
+  def() { echo $1; }
+  loop <<'  END'
+    one
+    two
+  END
 }
 
 return 2>/dev/null
